import React, { useState, useEffect } from "react";
import { useParams, useNavigate } from "react-router-dom";
import OrderGanttChart from "../components/OrderGanttChart";
import api from "../services/api";

export default function GanttPage({ user }) {
  const { orderId } = useParams();
  const navigate = useNavigate();
  const activeOrderId = orderId || "ORD-1042";

  const [ordersList, setOrdersList] = useState([]);
  const [loadingOrders, setLoadingOrders] = useState(true);
  const [priorityFilter, setPriorityFilter] = useState("ALL");
  const [statusFilter, setStatusFilter] = useState("ALL");

  useEffect(() => {
    api.get("/orders")
      .then((res) => {
        setOrdersList(res.data.orders || []);
      })
      .catch((err) => {
        console.error("Failed to fetch orders:", err);
      })
      .finally(() => setLoadingOrders(false));
  }, []);

  const filteredOrders = ordersList.filter((o) => {
    if (priorityFilter !== "ALL" && o.priority !== priorityFilter) return false;
    if (statusFilter !== "ALL" && o.status !== statusFilter) return false;
    return true;
  });

  return (
    <div style={{ padding: "1.5rem 2rem", maxWidth: "1600px", margin: "0 auto" }}>
      {/* Top Bar Navigation & Controls */}
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "1.5rem", flexWrap: "wrap", gap: "1rem" }}>
        <div>
          <h1 style={{ fontSize: "1.5rem", fontWeight: "700", color: "#0f172a", margin: 0 }}>
            Production Timeline &amp; Gantt Scheduling
          </h1>
          <p style={{ margin: "0.25rem 0 0", color: "#64748b", fontSize: "0.875rem" }}>
            Real-time shopfloor schedule generated by ML Predictions + Google OR-Tools CP-SAT
          </p>
        </div>

        {/* Order Selector & Filters */}
        <div style={{ display: "flex", alignItems: "center", gap: "0.75rem", flexWrap: "wrap" }}>
          <div>
            <label style={{ fontSize: "0.75rem", color: "#64748b", fontWeight: "600", display: "block", marginBottom: "0.2rem" }}>
              SELECT ORDER:
            </label>
            <select
              value={activeOrderId}
              onChange={(e) => navigate(`/orders/${e.target.value}/gantt`)}
              style={{
                padding: "0.4rem 0.8rem",
                borderRadius: "4px",
                border: "1px solid #cbd5e1",
                background: "#ffffff",
                fontFamily: "monospace",
                fontWeight: "700",
                fontSize: "0.85rem",
                color: "#0f172a"
              }}
            >
              {filteredOrders.map((o) => (
                <option key={o.id} value={o.id}>
                  {o.id} ({o.priority}) - {o.product_name || "Apparel"}
                </option>
              ))}
            </select>
          </div>

          <div>
            <label style={{ fontSize: "0.75rem", color: "#64748b", fontWeight: "600", display: "block", marginBottom: "0.2rem" }}>
              PRIORITY:
            </label>
            <select
              value={priorityFilter}
              onChange={(e) => setPriorityFilter(e.target.value)}
              style={{
                padding: "0.4rem 0.6rem",
                borderRadius: "4px",
                border: "1px solid #cbd5e1",
                background: "#ffffff",
                fontSize: "0.85rem",
                color: "#334155"
              }}
            >
              <option value="ALL">All Priorities</option>
              <option value="URGENT">URGENT</option>
              <option value="HIGH">HIGH</option>
              <option value="MEDIUM">MEDIUM</option>
              <option value="LOW">LOW</option>
            </select>
          </div>

          <div>
            <label style={{ fontSize: "0.75rem", color: "#64748b", fontWeight: "600", display: "block", marginBottom: "0.2rem" }}>
              STATUS:
            </label>
            <select
              value={statusFilter}
              onChange={(e) => setStatusFilter(e.target.value)}
              style={{
                padding: "0.4rem 0.6rem",
                borderRadius: "4px",
                border: "1px solid #cbd5e1",
                background: "#ffffff",
                fontSize: "0.85rem",
                color: "#334155"
              }}
            >
              <option value="ALL">All Statuses</option>
              <option value="RUNNING">RUNNING</option>
              <option value="QUEUED">QUEUED</option>
              <option value="BLOCKED">BLOCKED</option>
              <option value="COMPLETED">COMPLETED</option>
            </select>
          </div>
        </div>
      </div>

      {/* Main Order Gantt Component */}
      <OrderGanttChart
        orderId={activeOrderId}
        onOrderChange={(id) => navigate(`/orders/${id}/gantt`)}
      />
    </div>
  );
}
